### ISSUE TITLE
All but 500 files gone

### ISSUE THREAD

**Issue by mdhom** [rbonghi/docker-dropbox-app#36]
Hi,
I started the docker-dropbox-app yesterday for syncing two folders (`./documents` and `./mongo`) into my dropbox. I have my docker-compose configured as such:
```
  dropbox:
    image: rbonghi/dropbox:latest
    restart: always
    command: ["--fromLocal"]
    environment:
      - PYTHONUNBUFFERED=1
      - DROPBOX_APP_KEY=<>
      - DROPBOX_APP_SECRET=<>
      - DROPBOX_REFRESH_TOKEN=<>
    volumes:
      - ./documents:/dropbox
      - ./mongo:/dropbox/mongo
```
After starting the container, it successfully uploaded about 3500 files. I was able to see them in dropbox (on the website as well as on another dropbox client device).
Today I checked, and now in the documents folder, there are only exactly 500 files left, all of the others are gone. Can anyone help me understand how that could have happened?
Best regards,
Max
